const views={inbox:"Inbox",contacts:"Contatos",pipeline:"Pipeline",automations:"Automações",bots:"Bots",analytics:"Analytics"};
const seedContacts=[
{id:1,name:"Mariana Costa",phone:"+55 79 99111-2200",status:"lead",source:"WhatsApp",owner:"Adilson",last:"agora",tags:["Matrícula"],unread:true,bot:true},
{id:2,name:"Rafael Lima",phone:"+55 79 99881-4432",status:"customer",source:"WhatsApp",owner:"Adilson",last:"5 min",tags:["Suporte"],unread:false,bot:false},
{id:3,name:"Ana Beatriz",phone:"+55 79 98812-7311",status:"lead",source:"Site",owner:"Adilson",last:"18 min",tags:["Comercial"],unread:true,bot:true},
{id:4,name:"Lucas Rocha",phone:"+55 79 99920-1147",status:"customer",source:"WhatsApp",owner:"Adilson",last:"1h",tags:["Financeiro"],unread:false,bot:false},
{id:5,name:"Fernanda Melo",phone:"+55 79 98741-5580",status:"inactive",source:"Instagram",owner:"Adilson",last:"ontem",tags:["Follow-up"],unread:false,bot:true}
];
let contacts=JSON.parse(localStorage.getItem("daegonChatContacts")||"null")||seedContacts;
let selectedId=contacts[0].id,threadFilter="all",contactFilter="all",botOn=true;
const messages={
1:[{type:"bot",text:"Olá, Mariana! 👋 Como posso ajudar?",time:"09:01"},{type:"in",text:"Oi! Queria saber mais sobre matrícula.",time:"09:02"},{type:"out",text:"Claro! Posso te explicar as etapas e depois encaminhar para o setor responsável.",time:"09:03"}],
2:[{type:"in",text:"Não consigo acessar meu cadastro.",time:"08:51"},{type:"out",text:"Vou verificar com você. Pode me confirmar o e-mail usado no acesso?",time:"08:52"}],
3:[{type:"bot",text:"Olá! Recebemos seu contato pelo site.",time:"08:35"},{type:"in",text:"Quero falar com o comercial.",time:"08:36"}],
4:[{type:"in",text:"Pode me enviar a segunda via?",time:"ontem"},{type:"out",text:"Sim, já estou verificando.",time:"ontem"}],
5:[{type:"bot",text:"Olá! Ficamos à disposição caso queira retomar seu atendimento.",time:"ontem"}]
};
function $(s){return document.querySelector(s)} function $$(s){return [...document.querySelectorAll(s)]}
$$(".nav").forEach(b=>b.onclick=()=>{const id=b.dataset.view;$$(".view").forEach(v=>v.classList.toggle("active",v.id===id));$$(".nav").forEach(n=>n.classList.toggle("active",n===b));$("#pageTitle").textContent=views[id]});
function initials(n){return n.split(" ").slice(0,2).map(x=>x[0]).join("")}
function statusLabel(s){return s==="customer"?"Cliente":s==="inactive"?"Inativo":"Lead"}
function renderThreads(){const list=contacts.filter(c=>threadFilter==="all"||(threadFilter==="unread"&&c.unread)||(threadFilter==="bot"&&c.bot));$("#threadList").innerHTML=list.map(c=>`<div class="thread ${c.id===selectedId?"active":""}" data-id="${c.id}"><div class="ava">${initials(c.name)}</div><div><b>${c.name}</b><p>${(messages[c.id]||[]).at(-1)?.text||"Novo contato"}</p></div><div><time>${c.last}</time>${c.unread?'<span class="unread">•</span>':""}</div></div>`).join("");$$(".thread").forEach(t=>t.onclick=()=>{selectedId=+t.dataset.id;const c=contacts.find(x=>x.id===selectedId);if(c)c.unread=false;renderAll()})}
function renderChat(){const c=contacts.find(x=>x.id===selectedId)||contacts[0];$("#chatHead").innerHTML=`<div><b>${c.name}</b><small>${c.phone} · ${c.source}</small></div><span class="status">${statusLabel(c.status)}</span>`;$("#chatBody").innerHTML=(messages[c.id]||[]).map(m=>`<div class="msg ${m.type}">${m.text}<small>${m.time}</small></div>`).join("");$("#contactInfo").innerHTML=`<div class="ava">${initials(c.name)}</div><h3>${c.name}</h3><p>${c.phone}</p><p>Status: <b>${statusLabel(c.status)}</b></p><p>Responsável: <b>${c.owner}</b></p><p>Origem: <b>${c.source}</b></p><div>${c.tags.map(t=>'<span class="tag">'+t+'</span>').join("")}</div>`;$("#chatBody").scrollTop=$("#chatBody").scrollHeight}
function renderContacts(){const rows=contacts.filter(c=>contactFilter==="all"||c.status===contactFilter);$("#contactRows").innerHTML=rows.map(c=>`<tr><td>${c.name}<br><small>${c.phone}</small></td><td><span class="status">${statusLabel(c.status)}</span></td><td>${c.source}</td><td>${c.owner}</td><td>${c.last}</td><td>${c.tags.join(", ")}</td></tr>`).join("")}
function renderPipeline(){const lanes=[["lead","Novos"],["contact","Contato"],["proposal","Proposta"],["customer","Fechado"]];$("#kanban").innerHTML=lanes.map(([key,title],i)=>`<div class="lane"><h3>${title}</h3>${contacts.filter(c=>i===0?c.status==="lead":i===3?c.status==="customer":false).map(c=>'<div class="deal"><b>'+c.name+'</b><span>'+c.tags.join(" · ")+'</span></div>').join("")||'<div class="deal"><b>Oportunidade demo</b><span>R$ '+(1200+i*650).toLocaleString("pt-BR")+'</span></div>'}</div>`).join("")}
const autos=[["Boas-vindas WhatsApp","Mensagem nova → saudação → menu","Ativa"],["Lead sem resposta","24h sem retorno → criar follow-up","Ativa"],["Transferência humana","Palavra-chave → fila responsável","Ativa"],["Pós-atendimento","Conversa encerrada → pesquisa CSAT","Pausada"]];
function renderAutomations(){ $("#automationGrid").innerHTML=autos.map(a=>`<article class="auto-card"><span class="status">${a[2]}</span><h3>${a[0]}</h3><p>${a[1]}</p><footer><span>última execução: hoje</span><b>•••</b></footer></article>`).join("")}
function renderAll(){renderThreads();renderChat();renderContacts();renderPipeline();renderAutomations();localStorage.setItem("daegonChatContacts",JSON.stringify(contacts))}
$$("[data-thread-filter]").forEach(b=>b.onclick=()=>{$$("[data-thread-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");threadFilter=b.dataset.threadFilter;renderThreads()});
$$("[data-contact-filter]").forEach(b=>b.onclick=()=>{$$("[data-contact-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");contactFilter=b.dataset.contactFilter;renderContacts()});
$("#sendBtn").onclick=()=>{const text=$("#msgInput").value.trim();if(!text)return;(messages[selectedId]??=[]).push({type:"out",text,time:"agora"});$("#msgInput").value="";renderChat()};
$("#msgInput").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#sendBtn").click()}});
$("#botToggle").onclick=()=>{botOn=!botOn;$("#botToggle").textContent=botOn?"Bot ON":"Bot OFF";toast(botOn?"Bot ativado":"Bot pausado")};
const modal=$("#contactModal");["#newContactBtn","#newContactBtn2"].forEach(s=>$(s).onclick=()=>modal.classList.add("open"));$("#closeModal").onclick=()=>modal.classList.remove("open");modal.onclick=e=>{if(e.target===modal)modal.classList.remove("open")};
$("#contactForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);const id=Date.now();contacts.unshift({id,name:f.get("name"),phone:f.get("phone"),status:f.get("status"),source:"WhatsApp",owner:"Adilson",last:"agora",tags:[f.get("tag")||"Novo"],unread:false,bot:true});messages[id]=[{type:"bot",text:"Olá! 👋 Como posso ajudar?",time:"agora"}];selectedId=id;e.currentTarget.reset();modal.classList.remove("open");renderAll();toast("Contato criado")};
$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("daegonChatTheme",document.body.classList.contains("dark")?"dark":"light")};if(localStorage.getItem("daegonChatTheme")==="dark")document.body.classList.add("dark");
$("#saveBotBtn").onclick=()=>toast("Configurações do bot salvas");$("#newAutomationBtn").onclick=()=>toast("Construtor de automação em evolução");
function toast(t){const el=$("#toast");el.textContent=t;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1800)}
const command=$("#command"),cmdInput=$("#commandInput");$("#searchBtn").onclick=()=>{command.classList.add("open");cmdInput.focus()};function renderCommand(){const q=cmdInput.value.toLowerCase();const items=[...Object.entries(views).map(([id,label])=>({label,run:()=>{$('[data-view="'+id+'"]').click()}})),...contacts.map(c=>({label:c.name,run:()=>{selectedId=c.id;$('[data-view="inbox"]').click();renderAll()}}))].filter(x=>x.label.toLowerCase().includes(q));$("#commandResults").innerHTML=items.map((x,i)=>'<button class="command-item" data-ci="'+i+'">'+x.label+'</button>').join("");$$("[data-ci]").forEach(b=>b.onclick=()=>{items[+b.dataset.ci].run();command.classList.remove("open")})}cmdInput.oninput=renderCommand;document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();command.classList.add("open");renderCommand();cmdInput.focus()}if(e.key==="Escape"){command.classList.remove("open");modal.classList.remove("open")}});renderCommand();renderAll();